Simplify by modularizing script

diff --git a/src/bacterial-gc-content b/src/bacterial-gc-content
--- a/src/bacterial-gc-content
+++ b/src/bacterial-gc-content
@@ -16,7 +16,12 @@ DESCRIPTION:
 
 EXAMPLES:
 
+    # display the mean gc content of all Escherichia genomes
     $ biotk bacterial-gc-content Escherichia
+    # display the full annotation of all Escherichia genomes
+    $ biotk bacterial-gc-content --full Escherichia
+    # display the whole table
+    $ biotk bacterial-gc-content --full ""
 
 OPTIONS:
 
@@ -36,32 +41,51 @@ expr "$*" : ".*--help" > /dev/null && usage
 if [ $# -eq 0 ]; then > /dev/null && usage; fi
 
 readonly LOG_FILE="/tmp/$(basename "$0").log"
-BLUE=$(tput setab 4; tput setaf 7)
-RED=$(tput setaf 1)
-ERROR=$(tput setab 9; tput setaf 7)
-RESET=$(tput sgr 0)
 
-info()    { echo -e "${BLUE}INFO:  $@${RESET}"  | tee -a "$LOG_FILE" >&2 ; }
-warn()    { echo -e "${RED}WARN:  $@${RESET}"   | tee -a "$LOG_FILE" >&2 ; }
-error()   { echo -e "${ERROR}ERROR: $@${RESET}" | tee -a "$LOG_FILE" >&2 ; }
-fatal()   { echo -e "${ERROR}FATAL: $@${RESET}" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }
+info()    { echo -e "INFO:  $@"  | tee -a "$LOG_FILE" >&2 ; }
+warn()    { echo -e "WARN:  $@"   | tee -a "$LOG_FILE" >&2 ; }
+error()   { echo -e "ERROR: $@" | tee -a "$LOG_FILE" >&2 ; }
+fatal()   { echo -e "FATAL: $@" | tee -a "$LOG_FILE" >&2 ; exit 1 ; }
 
 cleanup() {
     rm -f "$LOG_FILE"
-    unset BLUE RED ERROR RESET
+    unset _db _full
+}
+
+_db="$BIO_SOURCE_DIR/data/prokaryotes.tsv"
+
+_head ()
+{
+    if expr "$*" : ".*--header" > /dev/null; then
+        sed -n '1p' "${_db}" \
+        | sed -e 's/^#//' \
+        | cut -f -13;
+    fi
+}
+
+_full ()
+{
+    _head "$*"
+    sed '1d' "${_db}" \
+        | awk -F'\t' "/${!#}/ {print}" \
+        | cut -f -13
+}
+
+_mean ()
+{
+    awk -F'\t' \
+        "/${!#}/{total += \$8; count++ } END { print total/count }" \
+        "${_db}" \
+        2> "$LOG_FILE" || \
+        error "Species not found. (Hint: Species name are usually case sensitive.)"
 }
 
 if [[ "${BASH_SOURCE[0]}" = "$0" ]]; then
     trap cleanup EXIT
 
     if  expr "$*" : ".*--full" > /dev/null; then
-        sed -n '1p'  $BIO_SOURCE_DIR/data/prokaryotes.tsv | sed -e 's/^#//' | cut -f -13;
-        awk -F'\t' "/${!#}/ {print}" "$BIO_SOURCE_DIR/data/prokaryotes.tsv" | cut -f -13
-
+        _full "$@"
     else
-        awk -F'\t' "/${!#}/{total += \$8; count++ } END { print total/count }" \
-        $BIO_SOURCE_DIR/data/prokaryotes.tsv \
-        2> "$LOG_FILE" || \
-        error "Species not found. (Hint: Species name are usually case sensitive.)"
+        _mean "$@"
     fi
 fi
